### ISSUE TITLE
Black waveform screen

### ISSUE THREAD

**Issue by CIURI86** [joan2937/piscope#1]
Hello ,

I'm facing a problem with piscope . The waveform screen remains black and I don't know how to debug  the problem . Tried on RPi , BananaPro , x86 hardware .Piscope connects to the pigpiod but no data.

This it was it looks like: http://postimg.org/image/mjo4n5pld/

What I'm doing wrong ? Tried with python 2.7 and 3.x no luck and Gtk3 .

**Comment by joan2937** [comment]
piscope will display a blank (black) screen until some level changes are seen.

On a Pi a simple way to trigger level changes is with PWM.  If you are not using GPIO 4 try `pigs p 4 128` from the command line (the command generates a square wave on GPIO 4).

**Comment by CIURI86** [comment]
Yep it works , piscope works fine on RPi (both piscope and pigpio) , BananaPro (piscope),x86 (piscope).

On BananaPro seems pigpio doesn't work at all , I started it with -a1 option , else error " initAllocDMAMem: mbox open failed", piscope connects but when I run "pigs p 4 128" on any GPIO nothing happens on piscope, and the pigpiod proces jumps to 150-200% cpu usage.

The banana is killing me , everithing was so fine on RPi

**Comment by joan2937** [comment]
pigpio uses several Broadcom peripherals on the Pi to sample the GPIO as effectively as it does.  The DMA peripheral to automatically round robin sample the GPIO as timed by the PCM peripheral and timestamped by the System Clock peripheral.

Unless those identical peripherals are present on the clone then pigpio will not work on that clone.

Anyhow, closing this as it's not a piscope issue.
