### ISSUE TITLE
libgtk-3 problem on RPi OS 64bit

### ISSUE THREAD

**Issue by h3retek** [joan2937/piscope#10]
Hi,

I had some problems with running PiScope in Rasberry Pi 4 8GB with Raspberry Pi OS

```
$ uname -a
Linux odin 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux
$ piscope &
[1] 5451
$ piscope: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

Even though libgtk-3 was installed: using `$ sudo apt install libgtk-3-dev`, and checking with:
```
$ sudo apt install libgtk-3-0
libgtk-3-0 is already the newest version (3.24.5-1+rpt2).
libgtk-3-0 set to manually installed.

```

Solution:
```
$ sudo dpkg --add-architecture armhf
$ sudo apt install libgtk-3-0:armhf
```

I could not find another way... and doing `sudo apt-get install gtk+-3.0` broke the aarch64 OS... something about an Nvidia armhf thing freaking out... although I have no idea what Nvidia is doing on my Pi?

```
sudo apt-get install gtk+-3.0
...
Note, selecting 'nvidia-settings-legacy-390xx:armhf' instead of 'nvidia-settings-gtk-390.116:armhf'
...
```
Although I must add, I did not `$ sudo dpkg --add-architecture armhf` on the run that broke my aarch64 OS. So maybe, if I had done only that, the Nvidia would have installed without any problems...

Anyway, it is what it is.

Could you maybe add this to the installation instructions? For future me...

**Comment by joan2937** [comment]
I will have a look at this but can not commit to a timescale.

**Comment by h3retek** [comment]
No problem.
