### ISSUE TITLE
Does piscope supports noise filter?

### ISSUE THREAD

**Issue by GF-Huang** [joan2937/piscope#8]

**Comment by joan2937** [comment]
piscope does not have any noise filters.

However piscope takes its data from pigpio which does have glitch and noise filters.  If the filters are set with pigs they will affect the data fed to piscope.

http://abyz.me.uk/rpi/pigpio/pigs.html#FG

http://abyz.me.uk/rpi/pigpio/pigs.html#FN

**Comment by GF-Huang** [comment]
Great, thanks your guide!

**Comment by GF-Huang** [comment]
@joan2937 Why I get `socket connect failed`?

![image](https://user-images.githubusercontent.com/4510984/103490246-7bbb6f00-4e55-11eb-88b3-061b9e5d35d6.png)
