### ISSUE TITLE
raspberry pi 4 piscope Unable to start

### ISSUE THREAD

**Issue by ycpss91255** [joan2937/piscope#9]
I installed it according to http://abyz.me.uk/rpi/pigpio/piscope.html
Then tried

## Pi (pre-built image)
```bash
wget abyz.me.uk/rpi/pigpio/piscope.tar
tar xvf piscope.tar
cd PISCOPE
make hf
make install
```

## Linux 64 bit X86/AMD (pre-built image)
```bash
wget abyz.me.uk/rpi/pigpio/piscope.tar
tar xvf piscope.tar
cd PISCOPE
make x86_64
make install
```
can't succeed

my rpi4 system is Ubuntu MATE 20.04

Pi error is
```bash
$ piscope
zsh: command not found: piscope

$ sudo piscope
sudo: unable to execute /usr/local/bin/piscope: No such file or directory

```
---
x86_64 error is
```bash
$ piscope
zsh: exec format error: piscope

$ sudo piscope
@: No such filepiscope: 1: cannot open @8
/usr/local/bin/piscope: 1: ELF: not found
/usr/local/bin/piscope: 2: Syntax error: word unexpected (expecting ")")
```

**Comment by joan2937** [comment]
What is the result (terminal output) of each of these commands?

1. wget abyz.me.uk/rpi/pigpio/piscope.tar
2. tar xvf piscope.tar
3. cd PISCOPE
4. make x86_64
5. make install

**Comment by ycpss91255** [comment]
> 1. wget abyz.me.uk/rpi/pigpio/piscope.tar

--2021-04-09 10:40:48--  http://abyz.me.uk/rpi/pigpio/piscope.tar
Resolving abyz.me.uk (abyz.me.uk)... 91.238.160.173
Connecting to abyz.me.uk (abyz.me.uk)|91.238.160.173|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 419840 (410K) [application/x-tar]
Saving to: ‘piscope.tar’

piscope.tar                100%[=====================================>] 410.00K   397KB/s    in 1.0s    

2021-04-09 10:40:50 (397 KB/s) - ‘piscope.tar’ saved [419840/419840]



> 2. tar xvf piscope.tar

PISCOPE/
PISCOPE/README
PISCOPE/piscope.x86_64
PISCOPE/LICENSE
PISCOPE/piscope.glade
PISCOPE/README.md
PISCOPE/piscope.h
PISCOPE/piscope.hf
PISCOPE/Makefile
PISCOPE/piscope.c

> 3. cd PISCOPE

not output

> 4. make x86_64

cp piscope.x86_64 piscope

> 5. make install

sudo install -m 0755 -d            /usr/local/bin
sudo install -m 0755 -d            /usr/share/piscope
sudo install -m 0755 piscope       /usr/local/bin
sudo install -m 0644 piscope.glade /usr/share/piscope

**Comment by joan2937** [comment]
Perhaps /usr/local/bin is not in your path?

Try /usr/local/bin/piscope

**Comment by ycpss91255** [comment]
$ /usr/local/bin/piscope
zsh: exec format error: /usr/local/bin/piscope

$ sudo /usr/local/bin/piscope
@: No such filepiscope: 1: cannot open @8
/usr/local/bin/piscope: 1: ELF: not found
/usr/local/bin/piscope: 2: Syntax error: word unexpected (expecting ")")

Seems to be the same

**Comment by joan2937** [comment]
I can't help any further.  I use it on a Ubuntu 20.4 system without issue.  I'm surprised Mate seems to make a difference but am not going to install Mate to find out what is going wrong.

**Comment by ycpss91255** [comment]
It's ok thanks for your help

**Comment by lxne** [comment]
Hi, I have almost the same issue on a raspberry pi 4 with latest bullseye 64bit.

Installation goes exactly as described above.

When I try `piscope &` I get…
```
[1] 13412
pi@raspberrypi:~ $ bash: /usr/local/bin/piscope: No such file or directory
```
The number increases with each try.

When I try `/usr/local/bin/piscope` the response is…
`bash: /usr/local/bin/piscope: No such file or directory`

Any ideas?

Best wishes.

**Comment by davthomaspilot** [comment]
Seems like a nice tool--wish it worked.  Same issue.

**Comment by aihrig** [comment]
EDIT:

Just found this: https://github.com/joan2937/piscope/issues/11

Needed to install gtk and then build - works now.

++++++++

I'm having the same problem on my RPi4 on the bookworm OS release. 

I ran the steps to install for a PI:

wget abyz.me.uk/rpi/pigpio/piscope.tar
tar xvf piscope.tar
cd PISCOPE
make hf
make install
